server.port=7072

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%-50.50C{1}){inverse} %clr([%-5level]){blue} %clr(%d{HH:mm:ss}){cyan} - %msg%n

spring.liquibase.enabled=true

spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5438/db
spring.datasource.password=root
spring.datasource.driver=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.open-in-view=false

logging.level.org.springframework.security=TRACE
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# application.properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.version=1.0.0
springdoc.swagger-ui.operationsSorter=method

bank.service.auth.secret.key=myverylongsecretkeymyverylongsecretkeymyverylongsecretkeymyverylongsecretkey